### ISSUE TITLE
missing/mismatched pdfs in odisha electoral rolls

### ISSUE THREAD

**Issue by anustubh** [in-rolls/electoral_rolls#1]
I found the discrepancies between the files in gs://in-electoral-rolls//Odisha_pdfs.gz.tar and the files listed in the Odisha.csv (metadata)
There are three AC constituencies for which PDFs are not available (AC 138 139 and 140), which are part of the district numbers 28 and 29.  These files appear in the metadeta but not in the actual downloaded electoral rolls. 

If you sort the files inside the Odisha_pdf.gz.tar file you will find that all files from eroll_27_105_001.pdf to 
eroll_27_110_225.pdf (those names do not exist in Odisha.csv) are actually the same file (of Size 282kb) with different names.

**Comment by soodoku** [comment]
Thanks @anustubh. 

By metadata on downloads, @anustubh means the CSV posted here: https://github.com/in-rolls/electoral_rolls/tree/master/odisha

thanks.

**Comment by soodoku** [comment]
Excel file highlighting the issue here: 
[Odisha_Files.xlsx](https://github.com/in-rolls/electoral_rolls/files/2823313/Odisha_Files.xlsx)

**Comment by anustubh** [comment]
Yes by metadata I am referring to the Odisha.csv.

**Comment by suriyan** [comment]
> Excel file highlighting the issue here:
> [Odisha_Files.xlsx](https://github.com/in-rolls/electoral_rolls/files/2823313/Odisha_Files.xlsx)

it seems XLSX file corrupted I cannot open it.

**Comment by suriyan** [comment]
I think not all PDF files in CSV (meta data) have been download correctly due to bad link (HTTP error 404)

Confirm the problem with duplicated PDF files (same size and content) so please discard.
